// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1wp7q0a8Yg1DKLbA0QZQ6DuQ7SSgDD74',
    appId: '1:259652702583:web:42835ef322b24cac3d1172',
    messagingSenderId: '259652702583',
    projectId: 'dstl-d22fc',
    authDomain: 'dstl-d22fc.firebaseapp.com',
    storageBucket: 'dstl-d22fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mFG_IOrWrbbo2MNpgwBR3peaPCdwCS8',
    appId: '1:259652702583:android:442c87321f1217bd3d1172',
    messagingSenderId: '259652702583',
    projectId: 'dstl-d22fc',
    storageBucket: 'dstl-d22fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3XXa2CYTQhU49s60U0h9IezYlBQ6bnP8',
    appId: '1:259652702583:ios:242b03ddfcf9aad93d1172',
    messagingSenderId: '259652702583',
    projectId: 'dstl-d22fc',
    storageBucket: 'dstl-d22fc.appspot.com',
    iosBundleId: 'com.dsit.dsitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3XXa2CYTQhU49s60U0h9IezYlBQ6bnP8',
    appId: '1:259652702583:ios:b2c943315ab0b26a3d1172',
    messagingSenderId: '259652702583',
    projectId: 'dstl-d22fc',
    storageBucket: 'dstl-d22fc.appspot.com',
    iosBundleId: 'com.dsit.dsitApp.RunnerTests',
  );
}
